"""Pipeline routes."""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any, List
from ..services import PipelineService
import os
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/api/pipeline", tags=["pipeline"])


@router.get("", response_model=Dict[str, Any])
async def get_pipeline_status():
    """
    Get pipeline status and phase information.
    
    Returns:
        - pipeline_status: Overall pipeline status
        - total_phases: Number of phases (7)
        - phases: List of phases with status and artifacts
        - overall_progress: Percentage complete
    
    Each phase includes:
        - phase: Phase identifier
        - name: Phase name
        - description: What the phase does
        - status: Current status (completed/running/pending)
        - artifacts: Output files generated by this phase
    """
    try:
        return PipelineService.get_pipeline_status()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get('/artifact')
async def get_pipeline_artifact(name: str):
    """
    Get the full contents of a pipeline artifact file from the backend/outputs directory.

    Parameters:
        - name: filename of the artifact (must match names returned by /api/pipeline)

    Returns:
        - artifact: filename
        - content: parsed JSON (for .json/.jsonl) or raw text
        - type: 'json'|'jsonl'|'text'
    """
    try:
        # determine base backend dir and search candidate locations
        base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
        search_dirs = [
            os.path.join(base_dir, 'outputs'),
            os.path.join(base_dir, 'analytics'),
            os.path.join(base_dir, 'data'),
            os.path.join(base_dir, 'config'),
        ]

        requested_path = None
        for search_dir in search_dirs:
            candidate_path = os.path.normpath(os.path.join(search_dir, name))
            if not candidate_path.startswith(os.path.abspath(search_dir)):
                continue
            if os.path.exists(candidate_path):
                requested_path = candidate_path
                break

        if not requested_path:
            raise HTTPException(status_code=404, detail='Artifact not found')

        # Read file
        _, ext = os.path.splitext(requested_path)
        if ext.lower() == '.jsonl':
            # parse JSONL into list
            items = []
            with open(requested_path, 'r', encoding='utf-8') as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        import json
                        items.append(json.loads(line))
                    except Exception:
                        items.append(line)
            return JSONResponse({'artifact': name, 'type': 'jsonl', 'content': items})
        else:
            with open(requested_path, 'r', encoding='utf-8') as fh:
                text = fh.read()
            # try parse JSON
            try:
                import json
                parsed = json.loads(text)
                return JSONResponse({'artifact': name, 'type': 'json', 'content': parsed})
            except Exception:
                return JSONResponse({'artifact': name, 'type': 'text', 'content': text})
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
